### ISSUE TITLE
Moving layers to different MIDI channel

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-ui#100]
From jerash:

change the midi channel from a layer, and change it to a channel already assigned to another layer. Then your synth is not listed anymore in zynthian-ui although it is receiving midi on the newly assigned channel and making sound.

**Comment by jofemodo** [comment]
Solved by only allowing to move to free MIDI channels.

**Comment by jerash** [comment]
ok, used channels do not appear anymore, so the problem won't come in anymore.
I've not used the "clone midi channel to" function yet, so I can't really argue if this could be an alternative as when you select an already used midi channel, then you could propose to clone the target midi chanel instead of changing it.
