### ISSUE TITLE
Segmentation fault when exiting Zynthian-UI

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-ui#126]
Random Segmentation Faults are raised when exiting zynthian-ui. It seems to be caused for threads not being ended in a proper way. The problem has been there for a long time, but hidden. With the status bar implementation, has raised to the surface.

**Comment by mheidt** [comment]
You didn't mean to close it,  right? Thursday, 23 May 2019, 07:47PM +02:00 from Jośe Fernando Moyano  notifications@github.com :

**Comment by jofemodo** [comment]
No no ... the problem is still alive ;-(

**Comment by jofemodo** [comment]
OK! I finally caught where the problem is. The jackpeak's "endJackpeak" function that is registered as "atexit" function is causing the problem. Disabling it solves the problem.

**Comment by riban-bw** [comment]
Let me take a look at that. I inherited that bit of code and didn't review it to closely. Maybe I should.

**Comment by riban-bw** [comment]
If you remove the atexit() registration then you should also remove endJackpeak() function which is now obsolete. I wonder though whether the randomness of this is dependant on whether initJackpeak() succeeds. If init fails to create the client then endJackpeak will seg fault because g_pJackClient has not been assigned. This should be caught by:
```
void endJackpeak() {
	if(g_pJackClient)
		jack_client_close(g_pJackClient);
}
```
I am not sure that matches the bug report though. The issue reported relates to zunthian-ui exit at which point one would not expect jackpeak to be initialising.

Is there a test scenario which (reliably) triggers this issue? I want to be sure that the fix (not closing the JACK client) does not have any adverse affect.
