### ISSUE TITLE
MIDI Looping back on usb devices even though 

### ISSUE THREAD

**Issue by 1st-BrainStormer** [zynthian/zynthian-ui#211]
**Describe the bug**
USB Midi devices looping back.
**To Reproduce**
1. Plug in USB midi Keyboard (Casio CDP-220 in this case)
2. Turn off local.
3. Start playing. notice it is looping back although not set to do so in the Midi Options>Ports menu

**Expected behavior**
Don't loop back if not configured to do so.

**Setup:**
 - SD-image: 2019-12-30-zynthianos-buster-lite-1.0.0
 - Hardware Config
        Raspberry Pi 4 Model B Rev 1.1
        Soundcard: HifiBerry DAC+ ADC PRO
        Display: ZynScreen 3.5 (v1)
        Wiring: MCP23017_ZynScreen
         GPIO Expander: MCP23017
 - Software Version
        zyncoder: master (8b7bfbd)
        zynthian-ui: master (0e8f5be)
        zynthian-sys: master (1739cc2)
        zynthian-data: master (ba48e1b)
        zynthian-webconf: master (9403cc0)

**Comment by jofemodo** [comment]
OK! I think i hunted the bug.
Please, update and test again!

**Comment by Mickinator** [comment]
Hi Jose and Bruce,

my doubble trigger problem seems to be solved too. It would be wonderful!

yours
Micki





Gesendet mit der Telekom Mail App
<https://www.telekom.de/unterwegs/apps-und-dienste/kommunikation/telekom-e-mail?wt_mc=alias_9998_unterwegs/apps-und-dienste/telekom-email#mail-app>

-----Original-Nachricht-----
Von: Jośe Fernando Moyano <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [zynthian/zynthian-ui] MIDI Looping back on usb devices even 
though (#211)
Datum: 10.03.2020, 17:33 Uhr
An: zynthian/zynthian-ui <zynthian-ui@noreply.github.com
<mailto:zynthian-ui@noreply.github.com> >
CC: Subscribed <subscribed@noreply.github.com
<mailto:subscribed@noreply.github.com> >

OK! I think i hunted the bug.
Please, update and test again!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zynthian/zynthian-ui/issues/211?email_source=notifications&email_token=ANJNSQNTKO6R5ELJ7J3WQFTRGZTXFA5CNFSM4LFC7PC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOMFCHA#issuecomment-597184796> 
, or unsubscribe

**Comment by 1st-BrainStormer** [comment]
Yep , that did it!   Thanks!
