### ISSUE TITLE
error stoping midi play

### ISSUE THREAD

**Issue by le51** [zynthian/zynthian-ui#225]
I'm feeding zythian with midi messages sent from a step sequencer.
When I push sequencer's stop button (midi log: "SYS STOP"), UI goes black and the following error message is shown:

"error stoping midi play"
" 'noneType' object has no attribute 'pid' "

**Comment by riban-bw** [comment]
This is because there is a mapping hardcoded for:
MIDI | CUIA 
-|-
START | START_MIDI_PLAY 
CONTINUE | START_MIDI_PLAY  
STOP | STOP_MIDI_PLAY

This in turn is hardcoded to trigger the MIDI recorder's start / stop playing. If a MIDI track is not selected then this fails. I have coincidentally found the same issue whilst building a step sequencer for Zynthian. I am about to propose changing the behaviour of this to allow configuration of MIDI timecode and transport messages.

**Comment by jofemodo** [comment]
It's solved. Please, update and test.

**Comment by le51** [comment]
It's okay ! Thanks.
