### ISSUE TITLE
Control zynthian with midi controller - SELECT NOT WORK 

### ISSUE THREAD

**Issue by gabrythe23** [zynthian/zynthian-ui#310]
hi to everyone,

I’m pretty new to zynthian but I’m in love with it! I’ve built a custom kit with rpb 3 (not the best but I’m very close to upgrading it!), screen (without touch atm), and innovation zero sl for control.

here’s the problem:

I’ve managed to set all the novation sl buttons with the right midi note number following the wiki Zynthian UI Users Guide - ZynthianWiki and everything is great except for the SELECT button, I’ve set two different controllers just to see if the problem was the novation but nope, SELECT does not work with midi. so sad, how can I fix it?

51 SELECT D#3

ps, if I use a standard pc USB keyboard select (assigned to enter button) works just as imagined

**Comment by jofemodo** [comment]
You should try using SWITCH_SELECT_SHORT instead.

SELECT CUIA action is not what you think. The name can be confusing. "SELECT" action receives a parameter (the velocity) and change the focus of the selected item on a list, but not perform the "click select" action. Also, it's not well suited for using from a keyboard because you can't control the velocity with precision. The action is intended for creating custom external controllers.

Regards,
